name: group
datasets:
  -
    name: imagenet-1k
    num_workers: 16
    base:
      image_dir_path: ${data_base}/imagenet/subset-32-classes/val
      annotation_path: ${data_base}/imagenet/imagenet_annotation_val_${number_of_classes}_classes.json
    novel:
      image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet/novel-8-classes/val
      annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet/novel-8-classes/imagenet1k_novel_classes_val.json

  -
    name: imagenet-a
    num_workers: 16
    base:
      image_dir_path: ${data_base}/imagenet-A/imagenet-a
      annotation_path: ${data_base}/imagenet-A/imagenet_a_annotation_val_${number_of_classes}_classes.json
    novel:
      image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-A/imagenet-a
      annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-A/imagenet_a_novel_classes_val.json

#  -
#    name: imagenet-c
#    num_workers: 16
#    base:
#      image_dir_path: ${data_base}/imagenet-C/imagenet-C-severity-5
#      annotation_path: ${data_base}/imagenet-C/imagenet_c_annotation_val_${number_of_classes}_classes.json
#    novel:
#      image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-C/novel-8-classes-imagenet-C-severity-5
#      annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-C/imagenet_c_novel_classes_val.json
  -
    name: imagenet-r
    num_workers: 16
    base:
      image_dir_path: ${data_base}/imagenet-R/imagenet-r
      annotation_path: ${data_base}/imagenet-R/imagenet_r_annotation_val_${number_of_classes}_classes.json
    novel:
      image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-R/imagenet-r
      annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-R/imagenet_r_novel_classes_val.json
  -
    name: imagenet-s
    num_workers: 16
    base:
      image_dir_path: ${data_base}/imagenet-S/sketch
      annotation_path: ${data_base}/imagenet-S/imagenet_s_annotation_val_${number_of_classes}_classes.json
    novel:
      image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-S/sketch
      annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-S/imagenet_s_novel_classes_val.json
  -
    name: imagenet-v2
    num_workers: 16
    base:
      image_dir_path: ${data_base}/imagenet-V2/imagenetv2-top-images-format-val
      annotation_path: ${data_base}/imagenet-V2/imagenet_v2_annotation_val_${number_of_classes}_classes.json
    novel:
      image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-V2/imagenetv2-top-images-format-val
      annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-V2/imagenet_v2_novel_classes_val.json