name: imagenet-s
num_workers: 16
base:
  image_dir_path: ${data_base}/imagenet-S/sketch
  annotation_path: ${data_base}/imagenet-S/imagenet_s_annotation_val_${number_of_classes}_classes.json
novel:
  image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-S/sketch
  annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-S/imagenet_s_novel_classes_val.json