name: imagenet-1k
num_workers: 16
base:
  image_dir_path: ${data_base}/imagenet/subset-32-classes/val
  annotation_path: ${data_base}/imagenet/imagenet_annotation_val_${number_of_classes}_classes.json
novel:
  image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet/novel-8-classes/val
  annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet/novel-8-classes/imagenet1k_novel_classes_val.json