name: imagenet-a
num_workers: 16
base:
  image_dir_path: ${data_base}/imagenet-A/imagenet-a
  annotation_path: ${data_base}/imagenet-A/imagenet_a_annotation_val_${number_of_classes}_classes.json
novel:
  image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-A/imagenet-a
  annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-A/imagenet_a_novel_classes_val.json