name: imagenet-v2
num_workers: 16
base:
  image_dir_path: ${data_base}/imagenet-V2/imagenetv2-top-images-format-val
  annotation_path: ${data_base}/imagenet-V2/imagenet_v2_annotation_val_${number_of_classes}_classes.json
novel:
  image_dir_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-V2/imagenetv2-top-images-format-val
  annotation_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/datasets/imagenet-V2/imagenet_v2_novel_classes_val.json