language: anas-awadalla/mpt-1b-redpajama-200b
flamingo: openflamingo/OpenFlamingo-3B-vitl-mpt1b
cross_attn_every_n_layers: 1
checkpoint_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/in-context-open-flamingo/open_flamingo_2-0/open_flamingo/prompt_train/of_ckpt_prompt_tokens/OF-3B-checkpoint_w_prompt_tokens.pt
alias: of-3b