language: anas-awadalla/mpt-7b
flamingo: openflamingo/OpenFlamingo-9B-vitl-mpt7b
cross_attn_every_n_layers: 4
checkpoint_path: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/in-context-open-flamingo/open_flamingo_2-0/open_flamingo/prompt_train/of_ckpt_prompt_tokens/OF-9B-checkpoint_w_prompt_tokens.pt
alias: of-9b