robust_prompting:
  use_robust_prompting: False
  number_of_robust_prompts: 0
  robust_scales:

number_of_classes: 16
number_of_media_prompts: 4
number_of_text_prompts_per_media: 3

dir: ./outputs/of-9b/train/imagenet-1k/class_16/rob_prompt_False/media_prompt_4_text_prompt_3/2024-08-12/22-12-28-agreeable-Jyoti/epoch_19_accuracy_0.98125