robust_prompting:
  use_robust_prompting: False
  number_of_robust_prompts: 0
  robust_scales:

number_of_classes: 8
number_of_media_prompts: 8
number_of_text_prompts_per_media: 3

dir: ../prompt_train/experiments/model_OF-9B/evaluate_dataset_imagenet-1k/classes_8/use_robust_prompting_False/media_prompts_8/text_prompts_per_media_3/2024-05-27_10-09-06/epoch_19_accuracy_0.9875