robust_prompting:
  use_robust_prompting: True # do not use robust during evaluation
  plan: scales
  robust_scales: #useless for now, hard encoding
    - 224
    - 112
    - 150
  number_of_robust_prompts: 4

number_of_classes: 8
number_of_media_prompts: 4
number_of_text_prompts_per_media: 3

dir: /dss/dssmcmlfs01/pn34sa/pn34sa-dss-0000/robustness/in-context-open-flamingo/open_flamingo_2-0/open_flamingo/attention_guidance/outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_4_text_prompt_3/2024-08-13/15-25-51-attentive-Penny/epoch_19_accuracy_0.995

