#dir: ./outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_4_text_prompt_3/2024-08-13/21-24-26-unfinished-Severiano/epoch_19_accuracy_0.985 # amplify 1.3, all 4 robust prompts
#dir: ./outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_4_text_prompt_3/2024-08-13/23-02-42-mountainous-Noor/epoch_19_accuracy_0.9725 # amplify 2, ori keeps the same, last 3 rob

#dir: ./outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_4_text_prompt_3/2024-08-14/10-01-13-adept-Timarie/epoch_19_accuracy_0.9775

dir: ./outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_3_text_prompt_3/2024-08-25/17-00-06-foolhardy-Martrel/epoch_49

number_of_classes: 8
number_of_media_prompts: 3
number_of_text_prompts_per_media: 3


robust_prompting:
  use_robust_prompting: True
  plan: five_crop
  robust_scales: #useless for now, hard encoding
    - 224
    - 112
    - 150
  number_of_robust_prompts: 5
  robust_prompting_at_last: False