#dir:  ./outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_8_text_prompt_3/2024-07-24/10-35-23-optimistic-Shirelle/epoch_25_accuracy_0.99
dir: ./outputs/of-9b/train/imagenet-1k/class_8/rob_prompt_True/media_prompt_8_text_prompt_3/2024-07-24/11-54-22-chilly-Teaya/epoch_15_accuracy_0.99
robust_prompting: robust-sit2